### PR TITLE
Add line flow

### PR DESCRIPTION
**Pull request by Voyager-sr2**
Flow test realization completed. Log added (but not configured, so logs everything to file). Some refactoring done, but will be continued while implementing Upgrade flow.

### CODE REVIEW

**Comment by sbglasius** [comment]
@Voyager-sr2  Love your example, but wonder if this is better suited in a separate example project like `spock-flow-example`? Then it can have it's own descriptive `README.md` to elaborate over your thoughts. 

Let me know what you think of this idea?

**Comment by Voyager-sr2** [comment]
Hello, @sbglasius ! Actually I have no idea how my commits appeared here. I've pushed them into forked repository.

**Comment by Voyager-sr2** [comment]
Sorry for such strange situation.

**Comment by sbglasius** [comment]
Apparently you created a pull-request for our upstream.

As said I think the code is interesting :-)

**Comment by sbglasius** [comment]
I think the only way you can remove this, is by removing the fork or making it private.

**Comment by Voyager-sr2** [comment]
I'll think about it and try. Thanks for advice.

**Pull request closed without merging**
